version: "3.9"
services:
  users:
    build: ./users
    ports:
      - "5000:5000"
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload

  orders:
    build: ./orders
    ports:
      - "5001:5001"
    command: uvicorn main:app --host 0.0.0.0 --port 5001 --reload

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - users
      - orders
      - mongo
    env_file: 
      - ./backend/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: backend_config
      MONGO_INITDB_LOGLEVEL: 1  # 0=INFO, 1=WARNING, 2=ERROR, 3=SEVERE
    command: ["--quiet", "--logpath", "/data/log/mongod.log"]
    volumes:
      - mongo_data:/data/db
      - ./mongo_logs:/data/log  # logs redirected here

  kong:
    image: kong:3.7
    container_name: kong
    restart: unless-stopped
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    ports:
      - "8000:8000" # Proxy (what clients call)
      - "8001:8001" # Admin API (for config/debug)
    volumes:
      - ./kong.yml:/etc/kong/kong.yml:ro
    depends_on:
      - backend
      - users
      - orders


volumes:
  mongo_data:
